version: '3.1'

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always
    
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 8080:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier